name: ci/cd

on:
  workflow_dispatch:
  push:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
  schedule:
  - cron: "20 4 24 * *"

jobs:

  core-builds:
    name: Erlang ${{ matrix.otp-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp-version: ['28', '27', '26']

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp-version }}
        rebar3-version: '3.25'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    #- name: Xref Checks
    #  run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Compile Unit Tests
      run: rebar3 as unit compile
    - name: Run Unit Tests
      run: rebar3 as unit lfe ltest -tunit
    - name: Compile Integration Tests
      run: rebar3 as integration compile
    - name: Run Integration Tests
      run: rebar3 as integration lfe ltest -tintegration
    #- name: Test Coverage
    #  run: rebar3 as test do proper -c, cover -v --min_coverage=0

  old-builds:
    name: Erlang ${{ matrix.otp-version }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        otp-version: ['25', '24']

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp-version }}
        rebar3-version: '3.22'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    #- name: Xref Checks
    #  run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Compile Unit Tests
      run: rebar3 as unit compile
    - name: Run Unit Tests
      run: rebar3 as unit lfe ltest -tunit
    - name: Compile Integration Tests
      run: rebar3 as integration compile
    - name: Run Integration Tests
      run: rebar3 as integration lfe ltest -tintegration
    #- name: Test Coverage
    #  run: rebar3 as test do proper -c, cover -v --min_coverage=0
